name: Gradle Build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: "Build with Gradle"
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v3

      - name: Cache Gradle Caches
        id: cache-gradle-caches
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          path: |
            ~/.gradle/caches
      - name: Cache Gradle Wrapper
        id: cache-gradle-wrapper
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/wrapper

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Build
        run: ./gradlew build --scan

      - name: Build Snapshot
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: rahulsom
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_sonatypePassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
        run: ./gradlew build snapshot --scan

      - name: Build Final
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-rc')
        env:
          DOCKER_USERNAME: rahulsom
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypeUsername: rahulsom
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_sonatypePassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
        run: ./gradlew -Prelease.useLastTag=true build final --scan

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
